JAWBONE_CLIENT_ID: aaa
JAWBONE_CLIENT_SECRET: aaa
TWITTER_API_KEY: aaa
TWITTER_API_SECRET: aaa
TWITTER_ACCESS_TOKEN: aaa
TWITTER_ACCESS_SECRET: aaa
production:
  TZ: Asia/Tokyo
  BASIC_AUTH: foo:bar
  JAWBONE_CLIENT_ID: aaa
  JAWBONE_CLIENT_SECRET: aaa
